version: '3'

services:
  master:
    build: .
    image: liamcottam/clusterio:latest
    container_name: factorio-master
    command: npx clusteriomaster run
    volumes:
      - clusterio_config:/config
    ports:
      - 1234:1234
    networks:
      - internal
  cluster:
    image: liamcottam/clusterio:latest
    depends_on:
      - master
    container_name: factorio-cluster
    command: npx clusterioslave run
    volumes:
    - clusterio_config:/config
    - instance_storage:/clusterio/instances
    ports:
      - 34197:34197/udp
      - 34198:34198/udp
    networks:
      - internal

networks:
  internal:

volumes:
  clusterio_config:
  instance_storage:
